In [2]:
import pandas as pd
from sklearn.model_selection import KFold #This is for the K-Fold Cross Validation
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np

In [3]:
data=pd.read_csv("Boston.CSV")
data.head()

,crim,zn,indus,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
x=data.iloc[:,:12].values
y=data.iloc[:,12].values

In [5]:
print(x)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]

In [6]:
print(y)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 30.3 34.6 34.9 32.9 24.1 42.3 48.5 50.  22.6 24.4 22.5 24.4 20.
 21.7 19.3 22.4 28.1 23.7 25.  23.3 28.7 21.5 23.  26.7 21.7 27.5 30.1
 44.8 50.  37.6 31.6 46.7 31.5 24.3 31.7 41.7 48.3 29.  24.  25.1 31.5
 23.7 23.3 22.  20.1 22.2 23.7 17.6 18.5 24.3 20.5 24.5 26.2 24.4 24.8
 29.6 42.8 21.9 20.9 44.  50.  36.  30.1 33.8 43.1 48.8 31.  36.5 22.8
 30.7 50.  43.5 20.7 21.1 25.2 24.4 35.2 32.4 32.  33.2 33.1 29.1 35.1
 45.4 35.4 46.  50.  32.2 22.  20.1 23.2 22.3 24.8 28.5 37.3 27.9 23.9
 21.7 28.6 27.1 20.3 22.5 29.  24.8 22.  26.4 33.1 36.1 28.4 33.4 28.2
 22.8 20.3 16.1 22.1 19.4 21.6 23.8 16.2 17.8 19.8 23.1 21.  23.8 23.1
 20.4 18.5 25.  24.6 23.  22.2 19.3 22.6 19.8 17.1 19.4 22.2 20.7 21.1
 19.5 18.5 20.6 19.  18.7 32.7 16.5 23.9 31.2 17.5 17.2 23.1 24.5 26.6
 22.9 24.1 18.6 30.1 18.2 20.6 17.8 21.7 22.7 22.6 25.  19.9 20.8 16.8
 21.9 27.5 21.9 23.1 50.  50.  50.  50.  50.  13.8 13.8 15.  13.9 13.3
 13.1 10.2 10.4 10.9 11.3 12.3  8.8  7.2 10.5  7.4 10.2 11.5 15.1 23.2
  9.7 13.8 12.7 13.1 12.5  8.5  5.   6.3  5.6  7.2 12.1  8.3  8.5  5.
 11.9 27.9 17.2 27.5 15.  17.2 17.9 16.3  7.   7.2  7.5 10.4  8.8  8.4
 16.7 14.2 20.8 13.4 11.7  8.3 10.2 10.9 11.   9.5 14.5 14.1 16.1 14.3
 11.7 13.4  9.6  8.7  8.4 12.8 10.5 17.1 18.4 15.4 10.8 11.8 14.9 12.6
 14.1 13.  13.4 15.2 16.1 17.8 14.9 14.1 12.7 13.5 14.9 20.  16.4 17.7
 19.5 20.2 21.4 19.9 19.  19.1 19.1 20.1 19.9 19.6 23.2 29.8 13.8 13.3
 16.7 12.  14.6 21.4 23.  23.7 25.  21.8 20.6 21.2 19.1 20.6 15.2  7.
  8.1 13.6 20.1 21.8 24.5 23.1 19.7 18.3 21.2 17.5 16.8 22.4 20.6 23.9
 22.  11.9]

# Creating K-Fold Corss Validation object with 5 folds. You can use any number of folds

In [7]:
kf=KFold(n_splits=5,shuffle=True)
kf

KFold(n_splits=5, random_state=None, shuffle=True)

In [8]:
model=LinearRegression()
model

LinearRegression()

# Split function is used to separet the training and testing data in each fold

In [9]:
kf.split(data) #This returns the indexes of training & testing data for each fold

In [10]:
list(kf.split(data))

[(array([  0,   2,   3,   6,   7,   8,   9,  10,  11,  12,  15,  16,  17,
          19,  20,  21,  22,  23,  24,  26,  27,  28,  29,  30,  31,  32,
          33,  34,  35,  36,  37,  38,  40,  44,  45,  46,  47,  49,  51,
          52,  53,  54,  56,  57,  58,  59,  60,  61,  63,  64,  67,  70,
          72,  73,  74,  75,  76,  77,  78,  80,  81,  83,  84,  85,  86,
          88,  89,  90,  92,  93,  94,  96,  97,  98, 100, 102, 103, 104,
         105, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
         119, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 133, 134,
         135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 146, 148, 149,
         150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
         163, 164, 165, 166, 168, 169, 171, 173, 174, 175, 176, 178, 179,
         180, 181, 182, 184, 185, 187, 188, 189, 190, 192, 194, 195, 196,
         197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 208, 209, 212,
         213, 214, 215, 216, 217, 218, 221, 222, 223, 224, 225, 226, 227,
         229, 230, 231, 232, 233, 236, 237, 239, 241, 242, 244, 245, 246,
         247, 249, 250, 251, 252, 253, 254, 257, 258, 259, 260, 262, 263,
         264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276,
         277, 278, 279, 280, 281, 282, 284, 285, 286, 287, 288, 289, 290,
         291, 292, 293, 294, 296, 298, 300, 301, 302, 303, 304, 305, 306,
         307, 308, 311, 312, 313, 315, 316, 318, 319, 320, 321, 323, 324,
         325, 326, 327, 328, 329, 331, 336, 337, 338, 339, 340, 342, 344,
         347, 348, 349, 350, 352, 353, 354, 355, 356, 357, 358, 359, 361,
         362, 363, 364, 366, 367, 368, 370, 372, 373, 374, 375, 376, 377,
         378, 379, 380, 382, 383, 384, 386, 388, 389, 390, 391, 392, 393,
         394, 395, 396, 397, 398, 399, 400, 401, 403, 406, 407, 408, 409,
         410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 423,
         424, 426, 427, 428, 429, 430, 431, 432, 433, 435, 437, 438, 439,
         440, 441, 444, 446, 447, 448, 449, 451, 452, 453, 454, 456, 457,
         458, 459, 460, 462, 464, 465, 466, 467, 468, 469, 470, 471, 472,
         474, 475, 477, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488,
         489, 490, 492, 493, 494, 495, 497, 498, 499, 500, 501, 502, 503,
         505]),
  array([  1,   4,   5,  13,  14,  18,  25,  39,  41,  42,  43,  48,  50,
          55,  62,  65,  66,  68,  69,  71,  79,  82,  87,  91,  95,  99,
         101, 106, 120, 121, 132, 145, 147, 167, 170, 172, 177, 183, 186,
         191, 193, 207, 210, 211, 219, 220, 228, 234, 235, 238, 240, 243,
         248, 255, 256, 261, 283, 295, 297, 299, 309, 310, 314, 317, 322,
         330, 332, 333, 334, 335, 341, 343, 345, 346, 351, 360, 365, 369,
         371, 381, 385, 387, 402, 404, 405, 422, 425, 434, 436, 442, 443,
         445, 450, 455, 461, 463, 473, 476, 478, 491, 496, 504])),
 (array([  0,   1,   2,   4,   5,   6,   8,  10,  11,  12,  13,  14,  15,
          18,  19,  20,  21,  25,  27,  28,  29,  30,  31,  32,  33,  34,
          35,  37,  38,  39,  40,  41,  42,  43,  44,  45,  47,  48,  50,
          53,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
          67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  79,  81,
          82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
          95,  96,  97,  99, 100, 101, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 116, 117, 118, 120, 121, 122, 123, 125, 126, 127,
         128, 130, 131, 132, 134, 136, 137, 138, 139, 140, 141, 142, 143,
         145, 147, 152, 154, 156, 157, 158, 159, 160, 162, 163, 165, 166,
         167, 168, 170, 171, 172, 174, 175, 176, 177, 178, 179, 180, 181,
         183, 184, 186, 188, 190, 191, 192, 193, 194, 196, 197, 198, 199,
         200, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
         214, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 228, 229,
         230, 231, 232, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243,
         244, 246, 247, 248, 250, 253, 254, 255, 256, 257, 258, 259, 260,
         261, 262, 265, 266, 267, 268, 269, 271, 272, 273, 274, 275, 276,
         278, 279, 280, 282, 283, 284, 286, 287, 288, 289, 291, 292, 293,
         294, 295, 297, 299, 300, 301, 302, 303, 304, 305, 307, 308, 309,
         310, 311, 312, 313, 314, 315, 317, 318, 319, 320, 321, 322, 323,
         324, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
         338, 339, 341, 342, 343, 345, 346, 347, 348, 349, 350, 351, 352,
         354, 355, 356, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367,
         368, 369, 370, 371, 372, 373, 374, 375, 378, 379, 380, 381, 382,
         383, 385, 386, 387, 393, 395, 399, 400, 401, 402, 403, 404, 405,
         406, 407, 408, 410, 411, 412, 413, 414, 415, 416, 417, 421, 422,
         423, 425, 426, 427, 428, 431, 432, 433, 434, 435, 436, 437, 438,
         439, 440, 441, 442, 443, 444, 445, 446, 448, 450, 452, 453, 455,
         456, 459, 460, 461, 462, 463, 465, 466, 467, 468, 469, 470, 471,
         473, 476, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488,
         489, 490, 491, 492, 493, 494, 495, 496, 497, 500, 501, 502, 503,
         504, 505]),
  array([  3,   7,   9,  16,  17,  22,  23,  24,  26,  36,  46,  49,  51,
          52,  54,  78,  80,  98, 102, 103, 104, 115, 119, 124, 129, 133,
         135, 144, 146, 148, 149, 150, 151, 153, 155, 161, 164, 169, 173,
         182, 185, 187, 189, 195, 201, 215, 226, 227, 233, 245, 249, 251,
         252, 263, 264, 270, 277, 281, 285, 290, 296, 298, 306, 316, 325,
         340, 344, 353, 357, 376, 377, 384, 388, 389, 390, 391, 392, 394,
         396, 397, 398, 409, 418, 419, 420, 424, 429, 430, 447, 449, 451,
         454, 457, 458, 464, 472, 474, 475, 477, 498, 499])),
 (array([  0,   1,   3,   4,   5,   7,   8,   9,  11,  12,  13,  14,  15,
          16,  17,  18,  19,  21,  22,  23,  24,  25,  26,  27,  28,  31,
          32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  45,
          46,  48,  49,  50,  51,  52,  54,  55,  57,  58,  59,  61,  62,
          63,  64,  65,  66,  67,  68,  69,  70,  71,  73,  74,  75,  76,
          77,  78,  79,  80,  81,  82,  84,  86,  87,  88,  89,  91,  92,
          93,  94,  95,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
         107, 109, 112, 113, 114, 115, 118, 119, 120, 121, 123, 124, 125,
         126, 127, 129, 130, 131, 132, 133, 134, 135, 137, 139, 142, 144,
         145, 146, 147, 148, 149, 150, 151, 152, 153, 155, 158, 159, 160,
         161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 172, 173, 174,
         175, 177, 178, 180, 182, 183, 185, 186, 187, 188, 189, 191, 192,
         193, 194, 195, 196, 197, 198, 201, 202, 204, 205, 206, 207, 208,
         209, 210, 211, 212, 213, 215, 216, 217, 219, 220, 221, 223, 224,
         225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 238, 240,
         242, 243, 244, 245, 247, 248, 249, 250, 251, 252, 254, 255, 256,
         257, 258, 260, 261, 262, 263, 264, 265, 266, 267, 268, 270, 271,
         272, 273, 276, 277, 278, 280, 281, 283, 284, 285, 287, 288, 289,
         290, 291, 293, 294, 295, 296, 297, 298, 299, 301, 302, 303, 306,
         307, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 321,
         322, 324, 325, 327, 330, 331, 332, 333, 334, 335, 337, 338, 340,
         341, 342, 343, 344, 345, 346, 347, 348, 350, 351, 352, 353, 354,
         355, 356, 357, 359, 360, 361, 362, 364, 365, 366, 367, 368, 369,
         370, 371, 375, 376, 377, 378, 380, 381, 382, 383, 384, 385, 386,
         387, 388, 389, 390, 391, 392, 394, 395, 396, 397, 398, 402, 403,
         404, 405, 408, 409, 411, 412, 413, 414, 415, 416, 417, 418, 419,
         420, 422, 423, 424, 425, 426, 428, 429, 430, 434, 436, 437, 439,
         440, 442, 443, 444, 445, 447, 449, 450, 451, 452, 454, 455, 456,
         457, 458, 459, 460, 461, 463, 464, 465, 466, 467, 469, 470, 471,
         472, 473, 474, 475, 476, 477, 478, 479, 480, 482, 483, 487, 488,
         489, 490, 491, 492, 493, 495, 496, 497, 498, 499, 500, 501, 503,
         504, 505]),
  array([  2,   6,  10,  20,  29,  30,  44,  47,  53,  56,  60,  72,  83,
          85,  90,  96, 108, 110, 111, 116, 117, 122, 128, 136, 138, 140,
         141, 143, 154, 156, 157, 171, 176, 179, 181, 184, 190, 199, 200,
         203, 214, 218, 222, 236, 237, 239, 241, 246, 253, 259, 269, 274,
         275, 279, 282, 286, 292, 300, 304, 305, 308, 320, 323, 326, 328,
         329, 336, 339, 349, 358, 363, 372, 373, 374, 379, 393, 399, 400,
         401, 406, 407, 410, 421, 427, 431, 432, 433, 435, 438, 441, 446,
         448, 453, 462, 468, 481, 484, 485, 486, 494, 502])),
 (array([  0,   1,   2,   3,   4,   5,   6,   7,   9,  10,  12,  13,  14,
          16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  28,  29,
          30,  32,  36,  39,  41,  42,  43,  44,  45,  46,  47,  48,  49,
          50,  51,  52,  53,  54,  55,  56,  57,  58,  60,  61,  62,  65,
          66,  68,  69,  71,  72,  74,  75,  76,  78,  79,  80,  82,  83,
          84,  85,  87,  88,  89,  90,  91,  95,  96,  97,  98,  99, 100,
         101, 102, 103, 104, 106, 107, 108, 110, 111, 112, 114, 115, 116,
         117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
         130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
         143, 144, 145, 146, 147, 148, 149, 150, 151, 153, 154, 155, 156,
         157, 158, 161, 163, 164, 167, 169, 170, 171, 172, 173, 174, 175,
         176, 177, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
         190, 191, 192, 193, 195, 198, 199, 200, 201, 202, 203, 204, 206,
         207, 209, 210, 211, 213, 214, 215, 218, 219, 220, 221, 222, 223,
         226, 227, 228, 231, 233, 234, 235, 236, 237, 238, 239, 240, 241,
         243, 244, 245, 246, 248, 249, 251, 252, 253, 254, 255, 256, 259,
         260, 261, 262, 263, 264, 267, 269, 270, 271, 272, 274, 275, 276,
         277, 279, 280, 281, 282, 283, 284, 285, 286, 287, 290, 292, 294,
         295, 296, 297, 298, 299, 300, 303, 304, 305, 306, 307, 308, 309,
         310, 314, 315, 316, 317, 318, 320, 321, 322, 323, 324, 325, 326,
         328, 329, 330, 332, 333, 334, 335, 336, 337, 339, 340, 341, 343,
         344, 345, 346, 347, 349, 351, 353, 356, 357, 358, 360, 361, 362,
         363, 364, 365, 366, 367, 368, 369, 371, 372, 373, 374, 375, 376,
         377, 379, 380, 381, 382, 384, 385, 387, 388, 389, 390, 391, 392,
         393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 404, 405, 406,
         407, 408, 409, 410, 411, 413, 415, 417, 418, 419, 420, 421, 422,
         424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436,
         438, 439, 441, 442, 443, 445, 446, 447, 448, 449, 450, 451, 453,
         454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466,
         467, 468, 469, 472, 473, 474, 475, 476, 477, 478, 480, 481, 482,
         483, 484, 485, 486, 491, 494, 496, 497, 498, 499, 500, 501, 502,
         503, 504]),
  array([  8,  11,  15,  27,  31,  33,  34,  35,  37,  38,  40,  59,  63,
          64,  67,  70,  73,  77,  81,  86,  92,  93,  94, 105, 109, 113,
         152, 159, 160, 162, 165, 166, 168, 178, 194, 196, 197, 205, 208,
         212, 216, 217, 224, 225, 229, 230, 232, 242, 247, 250, 257, 258,
         265, 266, 268, 273, 278, 288, 289, 291, 293, 301, 302, 311, 312,
         313, 319, 327, 331, 338, 342, 348, 350, 352, 354, 355, 359, 370,
         378, 383, 386, 403, 412, 414, 416, 423, 437, 440, 444, 452, 470,
         471, 479, 487, 488, 489, 490, 492, 493, 495, 505])),
 (array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  13,  14,
          15,  16,  17,  18,  20,  22,  23,  24,  25,  26,  27,  29,  30,
          31,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
          46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  59,  60,
          62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  77,
          78,  79,  80,  81,  82,  83,  85,  86,  87,  90,  91,  92,  93,
          94,  95,  96,  98,  99, 101, 102, 103, 104, 105, 106, 108, 109,
         110, 111, 113, 115, 116, 117, 119, 120, 121, 122, 124, 128, 129,
         132, 133, 135, 136, 138, 140, 141, 143, 144, 145, 146, 147, 148,
         149, 150, 151, 152, 153, 154, 155, 156, 157, 159, 160, 161, 162,
         164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 176, 177, 178,
         179, 181, 182, 183, 184, 185, 186, 187, 189, 190, 191, 193, 194,
         195, 196, 197, 199, 200, 201, 203, 205, 207, 208, 210, 211, 212,
         214, 215, 216, 217, 218, 219, 220, 222, 224, 225, 226, 227, 228,
         229, 230, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
         243, 245, 246, 247, 248, 249, 250, 251, 252, 253, 255, 256, 257,
         258, 259, 261, 263, 264, 265, 266, 268, 269, 270, 273, 274, 275,
         277, 278, 279, 281, 282, 283, 285, 286, 288, 289, 290, 291, 292,
         293, 295, 296, 297, 298, 299, 300, 301, 302, 304, 305, 306, 308,
         309, 310, 311, 312, 313, 314, 316, 317, 319, 320, 322, 323, 325,
         326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 338, 339,
         340, 341, 342, 343, 344, 345, 346, 348, 349, 350, 351, 352, 353,
         354, 355, 357, 358, 359, 360, 363, 365, 369, 370, 371, 372, 373,
         374, 376, 377, 378, 379, 381, 383, 384, 385, 386, 387, 388, 389,
         390, 391, 392, 393, 394, 396, 397, 398, 399, 400, 401, 402, 403,
         404, 405, 406, 407, 409, 410, 412, 414, 416, 418, 419, 420, 421,
         422, 423, 424, 425, 427, 429, 430, 431, 432, 433, 434, 435, 436,
         437, 438, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450,
         451, 452, 453, 454, 455, 457, 458, 461, 462, 463, 464, 468, 470,
         471, 472, 473, 474, 475, 476, 477, 478, 479, 481, 484, 485, 486,
         487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 498, 499, 502,
         504, 505]),
  array([  0,  12,  19,  21,  28,  32,  45,  57,  58,  61,  74,  75,  76,
          84,  88,  89,  97, 100, 107, 112, 114, 118, 123, 125, 126, 127,
         130, 131, 134, 137, 139, 142, 158, 163, 174, 175, 180, 188, 192,
         198, 202, 204, 206, 209, 213, 221, 223, 231, 244, 254, 260, 262,
         267, 271, 272, 276, 280, 284, 287, 294, 303, 307, 315, 318, 321,
         324, 337, 347, 356, 361, 362, 364, 366, 367, 368, 375, 380, 382,
         395, 408, 411, 413, 415, 417, 426, 428, 439, 456, 459, 460, 465,
         466, 467, 469, 480, 482, 483, 497, 500, 501, 503]))]

# Training the model with training set and validating with testing set in each fold and appending RSquared Value & MSE for each fold

In [11]:
MSEL=[]
RSL=[]

In [12]:
for i in list(kf.split(data)):
    model.fit(x[i[0],:],y[i[0]])
    RSL.append(model.score(x[i[0],:],y[i[0]]))
    y_pred=model.predict(x[i[1],:])
    MSEL.append(np.sqrt(mean_squared_error(y_pred,y[i[1]])))

# R-Squared value with Cross Validation

In [13]:
np.mean(RSL)*100

73.78350529364167

# Mean Squared Error with Cross Validation

In [14]:
np.mean(MSEL)

4.877961892099927